SELECT
SUBSTRING(ISSUE_COM,0,INSTR(ISSUE_COM,'|')) AS ISSUE,
SUBSTRING(SUBSTRING(ISSUE_COM,INSTR(ISSUE_COM,'|')+1),0,INSTR(SUBSTRING(ISSUE_COM,INSTR(ISSUE_COM,'|')+1),'|')) AS TABLE_TYPE,
SUBSTRING(ISSUE_COM,INSTR(ISSUE_COM,'|',-1)+1) AS ISSUE_TYPE,
DM_TABLE_NAME,
DM_COLUMN_NAME,
DM_COLUMN_DATA_TYPE,
DM_COLUMN_NULL_TYPE,
PRD_TABLE_NAME,
PRD_COLUMN_NAME,
PRD_COL_DATA_TYPE,
PRD_COLUMN_NULL_TYPE,
DRV_TABLE_NAME,
DRV_COL_NAME
FROM
(
SELECT DISTINCT
NVL(DM_TABLE_NAME,'') AS DM_TABLE_NAME,
NVL(DM_COLUMN_NAME,'') AS DM_COLUMN_NAME,
NVL(DM_COLUMN_DATA_TYPE,'') AS DM_COLUMN_DATA_TYPE,
NVL(DECODE(upper(DM_COLUMN_NULL_TYPE),'TRUE','NOT NULL','FALSE','NULL'),'') AS DM_COLUMN_NULL_TYPE,
NVL(PRD_TABLE_NAME,'') AS PRD_TABLE_NAME,
NVL(PRD_COLUMN_NAME,'') AS PRD_COLUMN_NAME,
NVL(PRD_COLUMN_DATA_TYPE,'') AS PRD_COL_DATA_TYPE,
NVL(DECODE(upper(PRD_COLUMN_NULL_TYPE),'TRUE','NOT NULL','FALSE','NULL'),'') AS PRD_COLUMN_NULL_TYPE,
CASE
WHEN TABLE_EXIST_IND='Y' AND
     (DM_COLUMN_DATA_TYPE = PRD_COLUMN_DATA_TYPE) AND (DM_COLUMN_NULL_TYPE=PRD_COLUMN_NULL_TYPE) THEN 'No|Existing Table|Column Matched'
WHEN TABLE_EXIST_IND='Y' AND (DM_COLUMN_DATA_TYPE <> PRD_COLUMN_DATA_TYPE) THEN 'Yes|Existing Table|Data Type Mismatched'
WHEN TABLE_EXIST_IND='Y' AND (DM_COLUMN_NULL_TYPE <> PRD_COLUMN_NULL_TYPE) THEN 'Yes|Existing Table|Not Null Mismatched'
WHEN TABLE_EXIST_IND='Y' AND  PRD_COLUMN_NAME IS NULL AND  DM_COLUMN_NAME IS NOT NULL THEN 'No|Existing Table|New Column Added'
WHEN TABLE_EXIST_IND='Y' AND  DM_COLUMN_NAME IS NULL THEN 'Yes|Existing Table|Column Deleted'
WHEN TABLE_EXIST_IND='N' THEN 'No|New Table|New Column'
END AS ISSUE_COM,
DRV_TABLE_NAME,
DRV_COL_NAME
FROM
(
SELECT
DM_TABLE_NAME,
DM_COLUMN_NAME,
DM_COLUMN_DATA_TYPE,
DM_COLUMN_NULL_TYPE,
SRC.PRD_TABLE_NAME,
SRC.PRD_COLUMN_NAME,
SRC.PRD_COLUMN_DATA_TYPE,
SRC.PRD_COLUMN_NULL_TYPE,
DRV_TABLE_NAME,
DRV_COL_NAME,
CASE WHEN EXT_PROD.PRD_TABLE_NAME IS NULL THEN 'N' ELSE 'Y' END AS TABLE_EXIST_IND
FROM
(
SELECT DISTINCT
DM.DM_TABLE_NAME,
DM.DM_COLUMN_NAME,
DM.DM_COLUMN_DATA_TYPE,
DM.upper(DM_COLUMN_NULL_TYPE) as DM_COLUMN_NULL_TYPE,
PRD.PRD_TABLE_NAME,
PRD.PRD_COLUMN_NAME,
PRD.PRD_COLUMN_DATA_TYPE,
PRD.upper(PRD_COLUMN_NULL_TYPE) as PRD_COLUMN_NULL_TYPE ,
COALESCE(DM.DM_TABLE_NAME,PRD.PRD_TABLE_NAME) AS DRV_TABLE_NAME,
COALESCE(DM.DM_COLUMN_NAME,PRD.PRD_COLUMN_NAME) AS DRV_COL_NAME
FROM STG_DEV_AUTO_DM_DDL DM
FULL OUTER JOIN STG_DEV_AUTO_PRD_DDL PRD
ON DM.DM_TABLE_NAME=PRD.PRD_TABLE_NAME
AND DM.DM_COLUMN_NAME=PRD.PRD_COLUMN_NAME
)SRC
LEFT OUTER JOIN STG_DEV_AUTO_PRD_DDL EXT_PROD
ON EXT_PROD.PRD_TABLE_NAME=SRC.DRV_TABLE_NAME
)SRC
)DRV
ORDER BY ISSUE_TYPE,DRV_TABLE_NAME,DRV_COL_NAME
;
                                                                                       