SELECT NAME||'=>'||'COMMENT ON COLUMN '||NAME||'.'||ATTNAME||' IS '||' ÃŠ'||TRANSLATE(TRANSLATE(DESCRIPTION,CHR(10),'Ã¢'),CHR(39),'Ãª')||'ÃŠ ;' AS TXT
FROM  _V_RELATION_COLUMN VR
WHERE EXISTS( SELECT 1 FROM  STG_DEV_AUTO_DM_DDL DM
WHERE VR.NAME=DM.DM_TABLE_NAME AND VR.ATTNAME=DM.DM_COLUMN_NAME) AND DESCRIPTION IS NOT NULL
ORDER BY NAME,ATTNUM
