DROP TABLE STG_DEV_AUTO_PRD_DDL IF EXISTS;
CREATE TABLE STG_DEV_AUTO_PRD_DDL
(
 PRD_TABLE_NAME VARCHAR(255),
 PRD_COLUMN_NAME VARCHAR(255),
 PRD_COLUMN_DATA_TYPE VARCHAR(100),
 PRD_COLUMN_NULL_TYPE VARCHAR(10),
 PRD_COLUMN_DEFAULT_VALUE VARCHAR(100)
 )
DISTRIBUTE ON (PRD_TABLE_NAME);