DROP TABLE STG_DEV_AUTO_STTM_DDL IF EXISTS;
CREATE TABLE STG_DEV_AUTO_STTM_DDL
(
 STTM_RULE_TYPE VARCHAR(255),
 STTM_MODIFIED_BY VARCHAR(255),
 STTM_TABLE_NAME VARCHAR(255),
 STTM_COLUMN_NAME VARCHAR(255),
 STTM_COLUMN_DATA_TYPE VARCHAR(100),
 STTM_COLUMN_NULL_TYPE VARCHAR(10),
 STTM_COLUMN_DEFAULT_VALUE VARCHAR(100),
 STTM_FILE_NAME VARCHAR(500)
 )
 DISTRIBUTE ON (STTM_TABLE_NAME);