DROP TABLE STG_DEV_AUTO_DM_DDL IF EXISTS;
CREATE TABLE STG_DEV_AUTO_DM_DDL
(
 DM_TABLE_NAME VARCHAR(255),
 DM_COLUMN_NAME VARCHAR(255),
 DM_COLUMN_DATA_TYPE VARCHAR(100),
 DM_COLUMN_NULL_TYPE VARCHAR(10),
 DM_COLUMN_DEFAULT_VALUE VARCHAR(100)
 )
 DISTRIBUTE ON (DM_TABLE_NAME);