SELECT TXT FROM
(
SELECT DM_TABLE_NAME,VR.ATTNUM,'TDM_'||DM_TABLE_NAME||'=>'||RPAD(DM.DM_COLUMN_NAME,40,' ')||
RPAD(DM.DM_COLUMN_DATA_TYPE,24,' ')||
RPAD(CASE WHEN DM.DM_COLUMN_NULL_TYPE='TRUE' THEN 'NOT NULL' ELSE '' END,10,' ')||
CASE  WHEN NVL(PRD.PRD_COLUMN_DEFAULT_VALUE,'')<>'' THEN 'DEFAULT '||PRD.PRD_COLUMN_DEFAULT_VALUE||','
ELSE ','
END AS TXT
FROM STG_DEV_AUTO_DM_DDL DM
INNER JOIN _V_RELATION_COLUMN VR
ON VR.NAME=DM.DM_TABLE_NAME
AND VR.ATTNAME=DM.DM_COLUMN_NAME
INNER JOIN STG_DEV_AUTO_PRD_DDL PRD
ON DM.DM_TABLE_NAME=PRD.PRD_TABLE_NAME
AND DM.DM_COLUMN_NAME=PRD.PRD_COLUMN_NAME
UNION
SELECT DM_TABLE_NAME,VR.ATTNUM,'TDM_'||DM_TABLE_NAME||'=>'||RPAD(DM.DM_COLUMN_NAME,40,' ')||
RPAD(DM.DM_COLUMN_DATA_TYPE,24,' ')||
RPAD(CASE WHEN DM.DM_COLUMN_NULL_TYPE='TRUE' THEN 'NOT NULL' ELSE '' END,10,' ')||
CASE 
     WHEN DM_COLUMN_NULL_TYPE='TRUE' AND DM_COLUMN_DATA_TYPE='INTEGER' THEN 'DEFAULT 0'||','
     WHEN DM_COLUMN_NULL_TYPE='TRUE' AND DM_COLUMN_DATA_TYPE='BIGINT' THEN 'DEFAULT -3'||','
ELSE ','
END AS TXT
FROM STG_DEV_AUTO_DM_DDL DM
INNER JOIN _V_RELATION_COLUMN VR
ON VR.NAME=DM.DM_TABLE_NAME
AND VR.ATTNAME=DM.DM_COLUMN_NAME
AND NOT EXISTS ( SELECT 1 FROM STG_DEV_AUTO_PRD_DDL PRD
                 WHERE DM.DM_TABLE_NAME=PRD.PRD_TABLE_NAME
                 AND DM.DM_COLUMN_NAME=PRD.PRD_COLUMN_NAME
                )
 )SRC                
ORDER BY DM_TABLE_NAME,ATTNUM