SELECT TXT
FROM
(
SELECT TABLENAME,SEQ,TABLENAME||'=>DISTRIBUTE ON ('||RTRIM(SEQ1_ATTNAME||SEQ2_ATTNAME||SEQ3_ATTNAME||SEQ4_ATTNAME||SEQ5_ATTNAME,',')||')' AS TXT
FROM
(
SELECT
TABLENAME,
1 as SEQ,
max(CASE WHEN DISTSEQNO=1 THEN ATTNAME||',' ELSE '' END) AS SEQ1_ATTNAME,
max(CASE WHEN DISTSEQNO=2 THEN ATTNAME||',' ELSE '' END) AS SEQ2_ATTNAME,
max(CASE WHEN DISTSEQNO=3 THEN ATTNAME||',' ELSE '' END) AS SEQ3_ATTNAME,
max(CASE WHEN DISTSEQNO=4 THEN ATTNAME||',' ELSE '' END) AS SEQ4_ATTNAME,
max(CASE WHEN DISTSEQNO=5 THEN ATTNAME||',' ELSE '' END) AS SEQ5_ATTNAME
FROM _v_table_dist_map  distmap
WHERE EXISTS ( SELECT 1 FROM
RAWSTG_SRC_D1..STG_DEV_AUTO_DM_DDL DM where 'TDM_'||DM.DM_TABLE_NAME=distmap.TABLENAME
)
GROUP BY TABLENAME,SEQ
)SRC
UNION ALL
SELECT TABLENAME,SEQ,TABLENAME||'=>ORGANIZE ON ('||RTRIM(SEQ1_ATTNAME||SEQ2_ATTNAME||SEQ3_ATTNAME||SEQ4_ATTNAME||SEQ5_ATTNAME,',')||')' AS TXT
FROM
(
SELECT
TABLENAME,
2 as SEQ,
max(CASE WHEN ORGSEQNO=1 THEN ATTNAME||',' ELSE '' END) AS SEQ1_ATTNAME,
max(CASE WHEN ORGSEQNO=2 THEN ATTNAME||',' ELSE '' END) AS SEQ2_ATTNAME,
max(CASE WHEN ORGSEQNO=3 THEN ATTNAME||',' ELSE '' END) AS SEQ3_ATTNAME,
max(CASE WHEN ORGSEQNO=4 THEN ATTNAME||',' ELSE '' END) AS SEQ4_ATTNAME,
max(CASE WHEN ORGSEQNO=5 THEN ATTNAME||',' ELSE '' END) AS SEQ5_ATTNAME
FROM _v_table_organize_column  distmap
WHERE EXISTS ( SELECT 1 FROM
RAWSTG_SRC_D1..STG_DEV_AUTO_DM_DDL DM where 'TDM_'||DM.DM_TABLE_NAME=distmap.TABLENAME
)
GROUP BY TABLENAME
)SRC
)SRC
order by TABLENAME,SEQ