SELECT TXT
FROM
(
SELECT
RELATION,CASE WHEN CONTYPE='p' THEN 1 ELSE 2 END AS CONTYPE_SEQ ,RELATION||'=>'||'ALTER TABLE '||RELATION||' ADD Constraint '||
CASE
     WHEN CONTYPE='u' THEN 'AK_'||RELATION||' UNIQUE ('
     WHEN CONTYPE='p' THEN 'PK_'||RELATION||' PRIMARY KEY ('
END
||RTRIM(
CASE WHEN SEQ1_ATTNAME='' THEN '' ELSE  SEQ1_ATTNAME||',' END||
CASE WHEN SEQ2_ATTNAME='' THEN '' ELSE  SEQ2_ATTNAME||',' END||
CASE WHEN SEQ3_ATTNAME='' THEN '' ELSE  SEQ3_ATTNAME||',' END||
CASE WHEN SEQ4_ATTNAME='' THEN '' ELSE  SEQ4_ATTNAME||',' END||
CASE WHEN SEQ5_ATTNAME='' THEN '' ELSE  SEQ5_ATTNAME||',' END||
CASE WHEN SEQ6_ATTNAME='' THEN '' ELSE  SEQ6_ATTNAME||',' END||
CASE WHEN SEQ7_ATTNAME='' THEN '' ELSE  SEQ7_ATTNAME||',' END||
CASE WHEN SEQ8_ATTNAME='' THEN '' ELSE  SEQ8_ATTNAME||',' END||
CASE WHEN SEQ9_ATTNAME='' THEN '' ELSE  SEQ9_ATTNAME||',' END||
CASE WHEN SEQ10_ATTNAME='' THEN '' ELSE  SEQ10_ATTNAME||',' END,',')
||');' AS TXT
FROM
(
SELECT
KD.RELATION,
KD.CONTYPE,
MAX(CASE WHEN KD.CONSEQ=1 THEN KD.ATTNAME ELSE '' END) AS SEQ1_ATTNAME,
MAX(CASE WHEN KD.CONSEQ=2 THEN KD.ATTNAME ELSE '' END) AS SEQ2_ATTNAME,
MAX(CASE WHEN KD.CONSEQ=3 THEN KD.ATTNAME ELSE '' END) AS SEQ3_ATTNAME,
MAX(CASE WHEN KD.CONSEQ=4 THEN KD.ATTNAME ELSE '' END) AS SEQ4_ATTNAME,
MAX(CASE WHEN KD.CONSEQ=5 THEN KD.ATTNAME ELSE '' END) AS SEQ5_ATTNAME,
MAX(CASE WHEN KD.CONSEQ=6 THEN KD.ATTNAME ELSE '' END) AS SEQ6_ATTNAME,
MAX(CASE WHEN KD.CONSEQ=7 THEN KD.ATTNAME ELSE '' END) AS SEQ7_ATTNAME,
MAX(CASE WHEN KD.CONSEQ=8 THEN KD.ATTNAME ELSE '' END) AS SEQ8_ATTNAME,
MAX(CASE WHEN KD.CONSEQ=9 THEN KD.ATTNAME ELSE '' END) AS SEQ9_ATTNAME,
MAX(CASE WHEN KD.CONSEQ=10 THEN KD.ATTNAME ELSE '' END) AS SEQ10_ATTNAME
FROM _v_relation_keydata KD where exists( select 1 from
 RAWSTG_SRC_D1..STG_DEV_AUTO_DM_DDL DM where 'TDM_'||DM.DM_TABLE_NAME=KD.RELATION)
and CONTYPE IN ('u','p')
GROUP BY RELATION,CONTYPE
)SRC
UNION ALL
SELECT
KD.RELATION,3 AS CONTYPE_SEQ ,KD.RELATION||'=>'||'ALTER TABLE '||KD.RELATION||' ADD '||' FOREIGN KEY ('||KD.ATTNAME||') REFERENCES '||KD.PKRELATION||'('||KD.PKATTNAME||');'
FROM _v_relation_keydata KD where exists( select 1 from
 RAWSTG_SRC_D1..STG_DEV_AUTO_DM_DDL DM where 'TDM_'||DM.DM_TABLE_NAME=KD.RELATION)
and CONTYPE IN ('f')
)SRC
ORDER BY RELATION,CONTYPE_SEQ